spring.application.name=gpu-farm-manager

# JWT Configuration
jwt.secret=${FARM_JWT_SECRET}
# Expiration: 24 hours (86400000 ms)
jwt.expiration-ms=86400000

# Datasouce Configuration
spring.datasource.url=${FARM_DB_URL}
spring.datasource.username=${FARM_DB_USERNAME}
spring.datasource.password=${FARM_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
